In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

In [ ]:
cd /content/drive/MyDrive/Datalab/practice

/content/drive/MyDrive/Datalab/practice

In [ ]:
!pip install sdv

Collecting sdv
  Downloading sdv-1.32.0-py3-none-any.whl.metadata (14 kB)
Collecting boto3<2.0.0,>=1.28 (from sdv)
  Downloading boto3-1.42.16-py3-none-any.whl.metadata (6.8 kB)
Collecting botocore<2.0.0,>=1.31 (from sdv)
  Downloading botocore-1.42.16-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: cloudpickle>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from sdv) (3.1.2)
Requirement already satisfied: graphviz>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from sdv) (0.21)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from sdv) (2.0.2)
Requirement already satisfied: pandas>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from sdv) (2.2.2)
Requirement already satisfied: tqdm>=4.29 in /usr/local/lib/python3.12/dist-packages (from sdv) (4.67.1)
Collecting copulas>=0.12.1 (from sdv)
  Downloading copulas-0.12.3-py3-none-any.whl.metadata (9.5 kB)
Collecting ctgan>=0.11.1 (from sdv)
  Downloading ctgan-0.11.1-py3-none-any.whl.metadata (10 kB)
Collecting deepecho>=0.7.0 (from sdv)
  Downloading deepecho-0.7.0-py3-none-any.whl.metadata (10 kB)
Collecting rdt>=1.18.2 (from sdv)
  Downloading rdt-1.18.2-py3-none-any.whl.metadata (10 kB)
Collecting sdmetrics>=0.21.0 (from sdv)
  Downloading sdmetrics-0.24.0-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: platformdirs>=4.0 in /usr/local/lib/python3.12/dist-packages (from sdv) (4.5.1)
Requirement already satisfied: pyyaml>=6.0.1 in /usr/local/lib/python3.12/dist-packages (from sdv) (6.0.3)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3<2.0.0,>=1.28->sdv)
  Downloading jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.17.0,>=0.16.0 (from boto3<2.0.0,>=1.28->sdv)
  Downloading s3transfer-0.16.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from botocore<2.0.0,>=1.31->sdv) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore<2.0.0,>=1.31->sdv) (2.5.0)
Requirement already satisfied: plotly>=5.10.0 in /usr/local/lib/python3.12/dist-packages (from copulas>=0.12.1->sdv) (5.24.1)
Requirement already satisfied: scipy>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from copulas>=0.12.1->sdv) (1.16.3)
Requirement already satisfied: torch>=2.3.0 in /usr/local/lib/python3.12/dist-packages (from ctgan>=0.11.1->sdv) (2.9.0+cpu)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.1.1->sdv) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.1.1->sdv) (2025.3)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from rdt>=1.18.2->sdv) (1.6.1)
Collecting Faker!=37.11.0,>=17 (from rdt>=1.18.2->sdv)
  Downloading faker-39.0.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=5.10.0->copulas>=0.12.1->sdv) (9.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=5.10.0->copulas>=0.12.1->sdv) (25.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.31->sdv) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->rdt>=1.18.2->sdv) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->rdt>=1.18.2->sdv) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.3.0->ctgan>=0.11.1->sdv) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.3.0->ctgan>=0.11.1->sdv) (3.0.3)
Downloading sdv-1.32.0-py3-none-any.whl (198 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.5/198.5 kB 7.6 MB/s eta 0:00:00
Downloading boto3-1.42.16-py3-none-any.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 8.1 MB/s eta 0:00:00
Downloading botocore-1.42.16-py3-none-any.whl (14.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/14.6 MB 65.2 MB/s eta 0:00:00
Downloading copulas-0.12.3-py3-none-any.whl (52 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.7/52.7 kB 2.7 MB/s eta 0:00:00
Downloading ctgan-0.11.1-py3-none-any.whl (25 kB)
Downloading deepecho-0.7.0-py3-none-any.whl (27 kB)
Downloading rdt-1.18.2-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.3/74.3 kB 4.9 MB/s eta 0:00:00
Downloading sdmetrics-0.24.0-py3-none-any.whl (198 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.3/198.3 kB 13.0 MB/s eta 0:00:00
Downloading faker-39.0.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 64.0 MB/s eta 0:00:00
Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Downloading s3transfer-0.16.0-py3-none-any.whl (86 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 5.5 MB/s eta 0:00:00
Installing collected packages: jmespath, Faker, botocore, s3transfer, rdt, deepecho, copulas, sdmetrics, ctgan, boto3, sdv
Successfully installed Faker-39.0.0 boto3-1.42.16 botocore-1.42.16 copulas-0.12.3 ctgan-0.11.1 deepecho-0.7.0 jmespath-1.0.1 rdt-1.18.2 s3transfer-0.16.0 sdmetrics-0.24.0 sdv-1.32.0

# data preprocessing

In [ ]:
import os
import shutil
import pandas as pd
import numpy as np

import torch
import torch.nn as nn
import torch.optim as optim

In [ ]:
df = pd.read_csv("../data/daily-median-income.csv")

In [ ]:
df.head()

    Entity Code  Year  Median (2021 prices)
0  Albania  ALB  1996              7.419331
1  Albania  ALB  2002              7.117155
2  Albania  ALB  2005              8.300112
3  Albania  ALB  2008              8.939034
4  Albania  ALB  2012              8.768968

In [ ]:
df = df.drop(columns=["Code"])

In [ ]:
df = df.rename(columns={
    "Median (2021 prices)": "value"
})

In [ ]:
df.head()

    Entity  Year     value
0  Albania  1996  7.419331
1  Albania  2002  7.117155
2  Albania  2005  8.300112
3  Albania  2008  8.939034
4  Albania  2012  8.768968

In [ ]:
global_min_year = df["Year"].min()
global_max_year = df["Year"].max()

countries = df["Entity"].unique()
years = range(global_min_year, global_max_year + 1)

full_index = pd.MultiIndex.from_product(
    [countries, years],
    names=["Entity", "Year"]
)

df_full = (
    df
    .set_index(["Entity", "Year"])
    .reindex(full_index)
    .reset_index()
)

In [ ]:
missing_df = df_full[df_full["value"].isna()]

In [ ]:
df_full.head()

    Entity  Year  value
0  Albania  1963    NaN
1  Albania  1964    NaN
2  Albania  1965    NaN
3  Albania  1966    NaN
4  Albania  1967    NaN

In [ ]:
## 수정 필요

In [ ]:
df_init = df_full.copy()
df_numeric = df_init[['value']]

df_numeric = df_numeric.interpolate(axis=0, limit_direction="both") # linear interpolation
df_numeric = df_numeric.fillna(df_numeric.mean()) # extra Nan as mean of every data
df_init['value'] = df_numeric['value']

In [ ]:
df_init

         Entity  Year     value
0       Albania  1963  7.419331
1       Albania  1964  7.419331
2       Albania  1965  7.419331
3       Albania  1966  7.419331
4       Albania  1967  7.419331
...         ...   ...       ...
12154  Zimbabwe  2021  3.047864
12155  Zimbabwe  2022  3.047864
12156  Zimbabwe  2023  3.047864
12157  Zimbabwe  2024  3.047864
12158  Zimbabwe  2025  3.047864

[12159 rows x 3 columns]

# model

In [ ]:
!pip show sdv

Name: sdv
Version: 1.32.0
Summary: Generate synthetic data for single table, multi table and sequential data
Home-page:
Author:
Author-email: "DataCebo, Inc." <info@sdv.dev>
License: BSL-1.1
Location: /usr/local/lib/python3.12/dist-packages
Requires: boto3, botocore, cloudpickle, copulas, ctgan, deepecho, graphviz, numpy, pandas, platformdirs, pyyaml, rdt, sdmetrics, tqdm
Required-by:

In [ ]:
from sdv.single_table import TVAESynthesizer
from sdv.metadata import SingleTableMetadata

metadata = SingleTableMetadata()
metadata.detect_from_dataframe(data=df_init)
metadata.update_column('value', sdtype='numerical')


discrete_cols = df_init.columns
# for col in discrete_cols:
#     metadata.update_column(col, sdtype='categorical')

model = TVAESynthesizer(
    metadata=metadata,
    epochs=20,
    batch_size=32,
    verbose=True
)

model.fit(df_init)

/usr/local/lib/python3.12/dist-packages/sdv/single_table/base.py:168: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
/usr/local/lib/python3.12/dist-packages/sdv/single_table/base.py:134: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(
Loss: 9.568: 100%|██████████| 20/20 [01:07<00:00,  3.38s/it]

In [ ]:
synthetic_export = model.sample(num_rows=len(df_init))
print(synthetic_export.head())

             Entity  Year      value
0              Iraq  1974  10.157039
1            Belize  1968  16.991430
2           Moldova  1978   6.517588
3  Colombia (urban)  1976   6.896169
4         Palestine  1975   7.188485

In [ ]:
 synthetic_export.sort_values(by=['Entity','Year'])

         Entity  Year     value
7072    Algeria  1963  8.421073
11099   Algeria  1964  8.027701
2193    Algeria  1965  6.785501
6289    Algeria  1965  6.692497
1154    Algeria  1966  8.505096
...         ...   ...       ...
5336   Zimbabwe  2020  4.169817
6013   Zimbabwe  2020  4.286454
11807  Zimbabwe  2021  3.486823
11084  Zimbabwe  2022  4.084243
5354   Zimbabwe  2025  3.191838

[12159 rows x 3 columns]

In [ ]:
from sdv.evaluation.single_table import evaluate_quality

quality_report = evaluate_quality(
    df_init,
    synthetic_export,
    metadata)

print("Overall similarity score:", quality_report)

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 3/3 [00:00<00:00, 108.44it/s]|
Column Shapes Score: 64.88%

(2/2) Evaluating Column Pair Trends: |██████████| 3/3 [00:00<00:00, 61.00it/s]|
Column Pair Trends Score: 49.29%

Overall Score (Average): 57.09%

Overall similarity score: <sdmetrics.reports.single_table.quality_report.QualityReport object at 0x7abad24d7cb0>

# evaluation

In [ ]:
synthetic_export.sort_values(by=['Entity','Year'])

         Entity  Year     value
7072    Algeria  1963  8.421073
11099   Algeria  1964  8.027701
2193    Algeria  1965  6.785501
6289    Algeria  1965  6.692497
1154    Algeria  1966  8.505096
...         ...   ...       ...
5336   Zimbabwe  2020  4.169817
6013   Zimbabwe  2020  4.286454
11807  Zimbabwe  2021  3.486823
11084  Zimbabwe  2022  4.084243
5354   Zimbabwe  2025  3.191838

[12159 rows x 3 columns]

In [ ]:
from sdv.evaluation.single_table import get_column_plot

fig = get_column_plot(
    real_data=df_init,
    synthetic_data=synthetic_export,
    column_name='value',
    metadata=metadata
)

fig.show()

In [ ]:
import numpy as np
import pandas as pd

dt_missing = dt.copy()

# 예: 데이터 5%를 NaN으로 만들기
missing_fraction = 0.05
for col in dt_missing.columns:
    dt_missing.loc[dt_missing.sample(frac=missing_fraction).index, col] = np.nan


from sklearn.metrics import mean_squared_error

col = 'Revenue'
mask = dt_missing[col].isna()
rmse = mean_squared_error(dt[col][mask], synthetic_export[col][mask], squared=False)
print(f'RMSE for {col}:', rmse)


col = 'Entity'
mask = dt_missing[col].isna()
accuracy = (synthetic_export[col][mask] == dt[col][mask]).mean()
print(f'Accuracy for {col}:', accuracy)

NameError: name 'dt' is not defined

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error

# 예시: df = 원본 데이터, synthetic_export = 합성 데이터

# 1. 원본 값이 있는 위치 선택
mask_existing = ~df['value'].isna()  # 원래 값이 있는 곳 True

# 2. 원래 값과 합성 데이터 값 선택
original_values = df.loc[mask_existing, 'value']
synthetic_values = synthetic_export.loc[mask_existing, 'value']

# 3. 비교 테이블 생성
comparison = pd.DataFrame({
    'original': original_values,
    'synthetic': synthetic_values
})
print(comparison.head())  # 확인용

# 4. 통계적 비교 (MSE, RMSE)
mse = mean_squared_error(original_values, synthetic_values)
rmse = mse ** 0.5
print("MSE:", mse)
print("RMSE:", rmse)

# 5. 시각화 비교
plt.figure(figsize=(10,5))
plt.plot(original_values.values, label='Original')
plt.plot(synthetic_values.values, label='Synthetic', alpha=0.7)
plt.legend()
plt.title("Original vs Synthetic Comparison")
plt.show()